FROM ubuntu:23.04

WORKDIR /app/bin

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list

RUN apt-get clean && apt-get update && apt-get install build-essential cmake tzdata unzip vim --no-install-recommends -y

# install third labs
RUN mkdir /app/resource
ADD ./resource /app/resource
RUN unzip /app/resource/hiredis-1.1.0.zip -d /app/resource/hiredis
RUN ls /app/resource/hiredis
RUN cd /app/resource/hiredis/hiredis-1.1.0 && make && make install

ENV TZ=Asia/Shanghai
