
FROM ubuntu:23.04

WORKDIR /app/bin

ENV DEBIAN_FRONTEND noninteractive

RUN sed -i s@/archive.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN sed -i s@/security.ubuntu.com/@/mirrors.aliyun.com/@g /etc/apt/sources.list
RUN apt-get clean && apt-get update

RUN apt-get install build-essential cmake tzdata --no-install-recommends -y

ENV TZ=Asia/Shanghai

